
# Variables
CC=g++
FLAGS=-O2 -g -Wall -std=gnu++17
NERD=&& echo "w00t!!!1!" | toilet --gay

#Default
all:
	$(CC) $(FLAGS) main.cpp src/*/*.cpp -o x.out $(NERD)

#Compile scanner program
# scanner: scanner.cpp
# 		g++ -O2 -Wall -std=gnu++11 -pthread scanner.cpp -o scanner

#Uninstall
clean:
		rm -v x.out

#