
# Variables
CC=g++
FLAGS=-O2 -g -Wall -std=gnu++17
NERD=&& echo "w00t!!!1!" | toilet --gay

#Default
all:
	$(CC) $(FLAGS) main.cpp src/*/*.cpp -o x.out $(NERD)

#Uninstall
clean:
		rm -v x.out

# Wipe local memory, ALL DATA WILL BE REMOVED!
clear:
		rm -v data/*

#